name = "Spop2"
uuid = "11b83ad2-e65e-47ba-870b-1ff818f3e30a"
authors = ["Kamil Erguler <k.erguler@cyi.ac.cy>", "Sean L. Wu <slwu89@berkeley.edu>"]
version = "1.1.0"

[deps]
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OpenSpecFun_jll = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
DSP = "0.7"
DifferentialEquations = "7.3"
Distributions = "0.25"
LaTeXStrings = "1.3"
OpenSpecFun_jll = "0.5"
PkgTemplates = "0.7"
Plots = "1.32"
SpecialFunctions = "2.1"
StatsBase = "0.33"
StatsFuns = "1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
